# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 097a892b5d5869bf62ec99c7bb34209b739a4b9ecd986373e4ba0bd59f121f36e138d6a1b318fc450364ef8451e9d752082a16f91225fcb1ec513f975ff88e86

test:
  secret_key_base: e42d85c9561583e475946ffbe9dd7bbcd01a0342491b1689c74201c1246b0cdf7e88d0f1f987ec3ac58f1fa70b2abbfd75baf92906a4b9c4b37e2b58d201bf47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
